'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import DashboardLayout from '@/components/DashboardLayout';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import { apiService } from '@/services/api';
import { extractApiErrorMessage } from '@/services/apiErrors';

type ProcessRow = { machineTypeId: string; name: string; months: Array<{ month: number; mttrValue: number | null; unit: 'HOURS' }> };
type HistoricalRow = { process: string; month: number; defectCount: number; defectCodes: string[] };
type ManualMttrResponse = { year: number; timeZone: string; availableYears: number[]; processes: ProcessRow[]; historical: HistoricalRow[] };
const cellKey = (machineTypeId: string, month: number) => `${machineTypeId}:${month}`;
const formatInput = (value: number | null) => value === null ? '' : String(value);
function parseInput(value: string): number | null | undefined { const trimmed = value.trim(); if (!trimmed) return null; const numericValue = Number(trimmed); return Number.isFinite(numericValue) && numericValue >= 0 ? numericValue : undefined; }

function ProductMttrContent() {
  const t = useTranslations('productQualityMttr'); const locale = useLocale(); const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear); const [data, setData] = useState<ManualMttrResponse | null>(null); const [values, setValues] = useState<Record<string, string>>({}); const [baseline, setBaseline] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const applyResponse = useCallback((next: ManualMttrResponse) => { const nextValues: Record<string, string> = {}; next.processes.forEach((process) => process.months.forEach((month) => { nextValues[cellKey(process.machineTypeId, month.month)] = formatInput(month.mttrValue); })); setData(next); setValues(nextValues); setBaseline(nextValues); }, []);
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); setSuccess(''); try { const response = await apiService.getManualProductQualityMttr(year, signal); if (!signal?.aborted) applyResponse(response.data as ManualMttrResponse); } catch (cause) { if (!signal?.aborted) setError(extractApiErrorMessage(cause, t('loadFailed'))); } finally { if (!signal?.aborted) setLoading(false); } }, [applyResponse, t, year]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const changedEntries = useMemo(() => data ? data.processes.flatMap((process) => process.months.filter((month) => values[cellKey(process.machineTypeId, month.month)] !== baseline[cellKey(process.machineTypeId, month.month)]).map((month) => ({ machineTypeId: process.machineTypeId, month: month.month, mttrValue: parseInput(values[cellKey(process.machineTypeId, month.month)] ?? '') }))) : [], [baseline, data, values]);
  const hasInvalidValue = changedEntries.some((entry) => entry.mttrValue === undefined);
  const save = async () => { if (saving || changedEntries.length === 0) return; if (hasInvalidValue) { setError(t('manualFormatError')); return; } setSaving(true); setError(''); try { const response = await apiService.saveManualProductQualityMttr({ year, entries: changedEntries.map((entry) => ({ ...entry, mttrValue: entry.mttrValue as number | null })) }); applyResponse(response.data as ManualMttrResponse); setSuccess(t('manualSaved')); } catch (cause) { setError(extractApiErrorMessage(cause, t('saveFailed'))); } finally { setSaving(false); } };
  const yearOptions = [...new Set([...(data?.availableYears ?? []), ...Array.from({ length: 12 }, (_, index) => currentYear - 1 + index), year])].sort((a, b) => b - a);
  const monthNames = Array.from({ length: 12 }, (_, index) => new Intl.DateTimeFormat(locale, { month: 'short', timeZone: 'UTC' }).format(new Date(Date.UTC(year, index, 1))));
  return <DashboardLayout title={t('title')}><main className="mx-auto w-full max-w-[1600px] space-y-6 p-4 md:p-6 lg:p-8" dir={locale === 'ar' ? 'rtl' : 'ltr'}>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold">{t('title')}</h1><p className="mt-1 text-sm text-slate-600">{t('manualDescription')}</p></div><label className="text-sm font-medium">{t('year')}<select value={year} onChange={(event) => setYear(Number(event.target.value))} className="ms-2 h-10 rounded-lg border border-slate-300 bg-white px-3">{yearOptions.map((item) => <option key={item}>{item}</option>)}</select></label></header>
    {success && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{success}</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
    <section className="rounded-2xl border bg-white shadow-sm">{loading ? <p role="status" className="p-10 text-center">{t('loading')}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><caption className="px-4 py-3 text-start font-semibold">{t('monthlyHoursHeading')}</caption><thead className="bg-slate-50"><tr><th className="sticky start-0 z-10 bg-slate-50 px-4 py-3 text-start">{t('process')}</th>{monthNames.map((month, index) => <th key={index} className="px-2 py-3 text-center">{month}</th>)}</tr></thead><tbody className="divide-y">{data?.processes.map((process) => <tr key={process.machineTypeId}><th className="sticky start-0 bg-white px-4 py-3 text-start font-semibold">{process.name}</th>{process.months.map((month) => { const key = cellKey(process.machineTypeId, month.month); return <td key={month.month} className="px-2 py-2"><input type="number" min="0" step="0.01" value={values[key] ?? ''} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} placeholder="—" aria-label={t('manualCellLabel', { process: process.name, month: monthNames[month.month - 1] })} className="h-9 w-20 rounded-lg border border-slate-300 px-2 text-center tabular-nums" /></td>; })}</tr>)}</tbody></table>{data?.processes.length === 0 && <p className="p-8 text-center text-slate-600">{t('noProcesses')}</p>}</div>}<div className="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-600">{t('manualInputHelp')}</p><button type="button" onClick={() => void save()} disabled={saving || loading || changedEntries.length === 0} className="rounded-xl bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving ? t('saving') : t('saveChanges')}</button></div></section>
    {!!data?.historical.length && <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">{t('historicalTitle', { year })}</h2><p className="mt-1 text-sm text-slate-600">{t('historicalContextHelp')}</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="bg-slate-50"><tr><th className="px-3 py-2 text-start">{t('process')}</th><th className="px-3 py-2 text-start">{t('month')}</th><th className="px-3 py-2 text-end">{t('historicalDefects')}</th><th className="px-3 py-2 text-start">{t('mainDefectCodes')}</th></tr></thead><tbody className="divide-y">{data.historical.map((row) => <tr key={`${row.process}:${row.month}`}><td className="px-3 py-2">{row.process}</td><td className="px-3 py-2">{monthNames[row.month - 1]}</td><td className="px-3 py-2 text-end">{row.defectCount}</td><td className="px-3 py-2">{row.defectCodes.join(', ')}</td></tr>)}</tbody></table></div></section>}
  </main></DashboardLayout>;
}

export default function ProductQualityMttrPage() { return <ProtectedRoute requiredRole="admin"><ProductMttrContent /></ProtectedRoute>; }
