'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import DashboardLayout from '@/components/DashboardLayout';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import { apiService } from '@/services/api';
import { extractApiErrorMessage } from '@/services/apiErrors';
import { averageSavedValues, buildHistoricalMatrix, parseManualMttrMinutes, type HistoricalMttrContext } from '@/services/productQualityMttr';

type ProcessRow = { machineTypeId: string; name: string; months: Array<{ month: number; mttrValue: number | null; unit: 'MINUTES' }> };
type ManualMttrResponse = { year: number; timeZone: string; availableYears: number[]; processes: ProcessRow[]; historical: HistoricalMttrContext[] };
const cellKey = (machineTypeId: string, month: number) => `${machineTypeId}:${month}`;
const formatInput = (value: number | null) => value === null ? '' : String(value);

function ProductMttrContent() {
  const t = useTranslations('productQualityMttr'); const locale = useLocale(); const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear); const [pendingYear, setPendingYear] = useState<number | null>(null); const [data, setData] = useState<ManualMttrResponse | null>(null);
  const [draftValues, setDraftValues] = useState<Record<string, string>>({}); const [savedValues, setSavedValues] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const applyResponse = useCallback((next: ManualMttrResponse) => { const authoritative: Record<string, string> = {}; next.processes.forEach((process) => process.months.forEach((month) => { authoritative[cellKey(process.machineTypeId, month.month)] = formatInput(month.mttrValue); })); setData(next); setSavedValues(authoritative); setDraftValues(authoritative); }, []);
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); setSuccess(''); try { const response = await apiService.getManualProductQualityMttr(year, signal); if (!signal?.aborted) applyResponse(response.data as ManualMttrResponse); } catch (cause) { if (!signal?.aborted) setError(extractApiErrorMessage(cause, t('loadFailed'))); } finally { if (!signal?.aborted) setLoading(false); } }, [applyResponse, t, year]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const changedEntries = useMemo(() => data ? data.processes.flatMap((process) => process.months.filter((month) => draftValues[cellKey(process.machineTypeId, month.month)] !== savedValues[cellKey(process.machineTypeId, month.month)]).map((month) => ({ machineTypeId: process.machineTypeId, month: month.month, mttrValue: parseManualMttrMinutes(draftValues[cellKey(process.machineTypeId, month.month)] ?? '') }))) : [], [data, draftValues, savedValues]);
  const isDirty = changedEntries.length > 0; const hasInvalidValue = changedEntries.some((entry) => entry.mttrValue === undefined);
  const save = async () => { if (saving || !isDirty) return; if (hasInvalidValue) { setError(t('manualFormatError')); return; } setSaving(true); setError(''); try { const response = await apiService.saveManualProductQualityMttr({ year, entries: changedEntries.map((entry) => ({ ...entry, mttrValue: entry.mttrValue as number | null })) }); applyResponse(response.data as ManualMttrResponse); setSuccess(t('manualSavedSuccessfully')); } catch (cause) { setError(extractApiErrorMessage(cause, t('saveFailed'))); } finally { setSaving(false); } };
  const requestYear = (nextYear: number) => { if (nextYear === year) return; if (isDirty) setPendingYear(nextYear); else setYear(nextYear); };
  const discardAndChangeYear = () => { if (pendingYear === null) return; setDraftValues(savedValues); setYear(pendingYear); setPendingYear(null); };
  const yearOptions = [...new Set([...(data?.availableYears ?? []), ...Array.from({ length: 12 }, (_, index) => currentYear - 1 + index), year])].sort((a, b) => b - a);
  const monthNames = Array.from({ length: 12 }, (_, index) => new Intl.DateTimeFormat(locale, { month: 'short', timeZone: 'UTC' }).format(new Date(Date.UTC(year, index, 1))));
  const savedNumber = (process: ProcessRow, month: number) => parseManualMttrMinutes(savedValues[cellKey(process.machineTypeId, month)] ?? '') ?? null;
  const processAverages = new Map((data?.processes ?? []).map((process) => [process.machineTypeId, averageSavedValues(process.months.map((month) => savedNumber(process, month.month)))]));
  const monthlyAverages = Array.from({ length: 12 }, (_, index) => averageSavedValues((data?.processes ?? []).map((process) => savedNumber(process, index + 1))));
  const overallAverage = averageSavedValues((data?.processes ?? []).flatMap((process) => process.months.map((month) => savedNumber(process, month.month))));
  const historicalMatrix = useMemo(() => buildHistoricalMatrix(data?.historical ?? []), [data?.historical]);
  const formatAverage = (value: number | null) => value === null ? '—' : `${new Intl.NumberFormat(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)} min`;

  return <DashboardLayout title={t('title')}><main className="mx-auto w-full max-w-[1700px] space-y-6 p-4 md:p-6 lg:p-8" dir={locale === 'ar' ? 'rtl' : 'ltr'}>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold">{t('title')}</h1><p className="mt-1 text-sm text-slate-600">{t('manualDescription')}</p></div><label className="text-sm font-medium">{t('year')}<select value={year} onChange={(event) => requestYear(Number(event.target.value))} className="ms-2 h-10 rounded-lg border border-slate-300 bg-white px-3">{yearOptions.map((item) => <option key={item}>{item}</option>)}</select></label></header>
    {pendingYear !== null && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><span>{t('discardYearQuestion')}</span><span className="flex gap-2"><button type="button" onClick={() => setPendingYear(null)} className="rounded-lg border bg-white px-3 py-2 font-semibold">{t('stay')}</button><button type="button" onClick={discardAndChangeYear} className="rounded-lg bg-amber-700 px-3 py-2 font-semibold text-white">{t('discardChanges')}</button></span></div>}
    {success && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{success}</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
    <section className="rounded-2xl border bg-white shadow-sm">{loading ? <p role="status" className="p-10 text-center">{t('loading')}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[1400px] text-sm"><caption className="px-4 py-3 text-start font-semibold">{t('monthlyMinutesHeading')}</caption><thead className="bg-slate-50"><tr><th className="sticky start-0 z-10 bg-slate-50 px-4 py-3 text-start">{t('process')}</th>{monthNames.map((month, index) => <th key={index} className="px-2 py-3 text-center">{month}</th>)}<th className="px-3 py-3 text-end">{t('processAverage')}</th></tr></thead><tbody className="divide-y">{data?.processes.map((process) => <tr key={process.machineTypeId}><th className="sticky start-0 bg-white px-4 py-3 text-start font-semibold">{process.name}</th>{process.months.map((month) => { const key = cellKey(process.machineTypeId, month.month); const dirty = draftValues[key] !== savedValues[key]; return <td key={month.month} className="px-2 py-2"><input type="number" min="0" step="0.01" value={draftValues[key] ?? ''} onChange={(event) => setDraftValues((current) => ({ ...current, [key]: event.target.value }))} placeholder="—" aria-label={t('manualCellLabel', { process: process.name, month: monthNames[month.month - 1] })} className={`h-9 w-20 rounded-lg border px-2 text-center tabular-nums ${dirty ? 'border-amber-400 bg-amber-50' : 'border-slate-300'}`} /></td>; })}<td className="px-3 py-2 text-end font-semibold">{formatAverage(processAverages.get(process.machineTypeId) ?? null)}</td></tr>)}<tr className="bg-slate-50 font-semibold"><th className="sticky start-0 bg-slate-50 px-4 py-3 text-start">{t('monthlyAverage')}</th>{monthlyAverages.map((average, index) => <td key={index} className="px-2 py-3 text-center">{formatAverage(average)}</td>)}<td className="px-3 py-3 text-end">{formatAverage(overallAverage)}</td></tr></tbody></table>{data?.processes.length === 0 && <p className="p-8 text-center text-slate-600">{t('noProcesses')}</p>}</div>}<div className="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">{t('overallAverage')}: {formatAverage(overallAverage)}</p>{isDirty && <p role="status" className="mt-1 text-sm font-medium text-amber-700">{t('unsavedChanges')}</p>}</div><button type="button" onClick={() => void save()} disabled={saving || loading || !isDirty} className="rounded-xl bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving ? t('saving') : t('saveChanges')}</button></div></section>
    {historicalMatrix.processes.length > 0 && <section className="rounded-2xl border bg-white shadow-sm"><div className="p-5"><h2 className="text-lg font-semibold">{t('historicalTitle', { year })}</h2><p className="mt-1 text-sm text-slate-600">{t('historicalContextHelp')}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1400px] text-sm"><thead className="bg-slate-50"><tr><th className="sticky start-0 bg-slate-50 px-4 py-3 text-start">{t('process')}</th>{monthNames.map((month, index) => <th key={index} className="px-2 py-3 text-center">{month}</th>)}<th className="px-3 py-3 text-end">{t('total')}</th></tr></thead><tbody className="divide-y">{historicalMatrix.processes.map((process) => <tr key={process.process}><th className="sticky start-0 bg-white px-4 py-3 text-start">{process.process}</th>{process.months.map((month) => <td key={month.month} className="px-2 py-3 text-center"><span className="block font-semibold">{month.defectCount}</span>{month.defectCodes.length > 0 && <span className="mt-1 block whitespace-nowrap text-xs text-slate-500">{month.defectCodes.join(', ')}</span>}</td>)}<td className="px-3 py-3 text-end font-semibold">{process.total}</td></tr>)}<tr className="bg-slate-50 font-semibold"><th className="sticky start-0 bg-slate-50 px-4 py-3 text-start">{t('monthlyTotal')}</th>{historicalMatrix.monthlyTotals.map((total, index) => <td key={index} className="px-2 py-3 text-center">{total}</td>)}<td className="px-3 py-3 text-end">{historicalMatrix.finalTotal}</td></tr></tbody></table></div><p className="border-t p-4 font-semibold">{t('finalHistoricalDefects')}: {historicalMatrix.finalTotal}</p></section>}
  </main></DashboardLayout>;
}

export default function ProductQualityMttrPage() { return <ProtectedRoute requiredRole="admin"><ProductMttrContent /></ProtectedRoute>; }
