export enum AccountAccessErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_PENDING_APPROVAL = 'ACCOUNT_PENDING_APPROVAL',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  ACCOUNT_ROLE_NOT_ALLOWED = 'ACCOUNT_ROLE_NOT_ALLOWED',
}
