export enum RefreshTokenErrorCode {
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID_OR_EXPIRED = 'REFRESH_TOKEN_INVALID_OR_EXPIRED',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED',
  REFRESH_USER_NOT_FOUND = 'REFRESH_USER_NOT_FOUND',
  REFRESH_TOKEN_SUBJECT_INVALID = 'REFRESH_TOKEN_SUBJECT_INVALID',
  REFRESH_TOKEN_WRONG_TYPE = 'REFRESH_TOKEN_WRONG_TYPE',
}
